apiVersion: v1
kind: Service
metadata:
  name: kubernetes-jsm-api
  labels:
    app: kubernetes-jsm-api
spec:
  selector:
    app: kubernetes-jsm-api
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud